CREATE DATABASE mywallet;
\connect mywallet

CREATE USER mywallet WITH PASSWORD 'mywallet';
CREATE SCHEMA IF NOT EXISTS mywallet AUTHORIZATION mywallet;
ALTER SCHEMA mywallet OWNER TO mywallet;

ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA mywallet GRANT ALL PRIVILEGES ON TABLES TO mywallet;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA mywallet GRANT ALL PRIVILEGES ON SEQUENCES TO mywallet;
ALTER DEFAULT PRIVILEGES FOR USER postgres IN SCHEMA mywallet GRANT EXECUTE ON ROUTINES TO mywallet;
